### ISSUE TITLE
Django trims whitespaces in json mode

### ISSUE THREAD

**Issue by RANUX** [django-ace/django-ace#22]
Django trims whitespaces in json mode, so i found fix. I added code:
```
        if (mode == "json") {
            editor.setValue(JSON.stringify(JSON.parse(editor.getSession().getValue()), null, 2));
        }
```
to  `django_ace/static/django_ace/widgets.js` in `apply_widget()` (151 line). If this fix ok, i can create pull request. 
Thanks.

**Comment by JulienPalard** [comment]
I'm not a js dev, so I wont be able to tell if it's good or not, can you explain why it fixes it?

**Comment by RANUX** [comment]
I use django_ace in admin panel for editing json code. By default, it trims whitespaces before save and it's not easy to read or modify JSON code later. My fix is reformat  json before it will be shown in editor.

**Comment by fdemmer** [comment]
I suspect @RANUX is using a [JSONField](https://docs.djangoproject.com/en/3.2/ref/models/fields/#django.db.models.JSONField), which does not preserve text formatting. I'd say this issue is outside the scope of django-ace and a possible solution would be to provide a custom encoder to the JSONField, that recreates the indentation, e.g.:

```
class FixedIndentJSONEncoder(json.JSONEncoder):
    def __init__(self, *args, **kwargs):
        kwargs['indent'] = 4
        super().__init__(*args, **kwargs)


class MyModel(models.Model):
    data = models.JSONField(default=dict, encoder=FixedIndentJSONEncoder)
```
